INSERT INTO products (id, name, slug, description, price_cents, currency, image_base64, is_active, created_at)
VALUES 
('1', 'Digital Marketing Masterclass', 'digital-marketing-masterclass', 'Complete guide to digital marketing strategies. Learn the complete digital marketing ecosystem including SEO, social media marketing, email campaigns, and analytics.', 9900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('2', 'Web Development Toolkit', 'web-development-toolkit', 'Essential tools and resources for web developers. A comprehensive collection of web development tools, templates, and resources.', 14900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('3', 'Social Media Content Pack', 'social-media-content-pack', 'Premium social media templates and graphics. Includes Instagram, Facebook, Twitter, and LinkedIn templates.', 7900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('4', 'Business Plan Template', 'business-plan-template', 'Professional business plan template with financial projections. Perfect for startups and small businesses.', 4900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('5', 'E-commerce Starter Kit', 'ecommerce-starter-kit', 'Complete e-commerce solution with templates, guides, and tools. Launch your online store quickly.', 19900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('6', 'SEO Optimization Guide', 'seo-optimization-guide', 'Comprehensive SEO guide with tools and strategies. Improve your website ranking and visibility.', 8900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('7', 'Photoshop Template Bundle', 'photoshop-template-bundle', 'Collection of premium Photoshop templates for various design needs. Includes social media, print, and web design templates.', 12900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('8', 'Video Editing Course', 'video-editing-course', 'Comprehensive video editing course for beginners to advanced users. Learn professional video editing techniques with popular software.', 15900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('9', 'Productivity Planner', 'productivity-planner', 'Digital productivity planner with templates for daily, weekly, and monthly planning. Boost your efficiency and organization.', 5900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('10', 'UI/UX Design System', 'ui-ux-design-system', 'Complete UI/UX design system with components, templates, and guidelines. Perfect for designers and developers.', 17900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('11', 'Content Creation Toolkit', 'content-creation-toolkit', 'Essential tools for content creators including templates, guides, and resources. Perfect for bloggers, vloggers, and social media managers.', 9900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW()),
('12', 'Email Marketing Templates', 'email-marketing-templates', 'Professional email marketing templates for various campaigns. Includes newsletters, promotions, and automated sequences.', 6900, 'USD', 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAnElEQVR42u3RAQ0AAAgDoL/UyRleGzBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnKnagIGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgfGfseOLaAFMJGxJAAAAAElFTkSuQmCC', true, NOW());